version: '3.8'

services:
  reset-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reset-backend
    restart: unless-stopped
    ports:
      - "80:3000" # Mapea el puerto 80 del VPS (Droplet) al 3000 del contenedor
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    # Opcional: Si quieres montar un volumen para logs u otras cosas
    # volumes:
    #   - ./logs:/app/logs
